### PR TITLE
improve svg format detection

### PR DESCRIPTION
**Pull request by selul**
The SVG decoder fails to detect sources that start with `<svg` although this is a valid format.

Here you have an example: https://www.codeinwp.com/wp-content/uploads/2018/05/codeinwp-logo.svg

I've tried to register this into the current decoder.

What do you think?

### CODE REVIEW

**Comment by DarthSim** [comment]
LGTM. But let's DRY it a little. Something like this:

```go
decode := func(io.Reader) (image.Image, error) { ... }
decodeConfig := func(io.Reader) (image.Config, error) { ... }

image.RegisterFormat("svg", "<?xml", decode, decodeConfig)
image.RegisterFormat("svg", "<svg", decode, decodeConfig)
```

**Comment by selul** [comment]
Thanks for the feedback, @DarthSim. I've applied your suggestion.

**Comment by DarthSim** [comment]
Thanks for your contribution! Released in v2.2.5

**Comment by DarthSim** [comment]
I'd be very appreciated if you could spend some time filling our [survey form](https://evilmartians.typeform.com/to/A0OfqB)

**Pull request merged**
