### PR TITLE
Vary: Accept response header

### PR DESCRIPTION
**Pull request by leopangan**
For the Accept request header to be considered by Google Cloud CDN, the response must have Vary: Accept header. See https://cloud.google.com/cdn/docs/caching#vary_headers

### CODE REVIEW

**Comment by DarthSim** [comment]
Hi!

Thanks for the contribution! Could you also add client hints headers to `Vary` when ones are enabled?

**Comment by leopangan** [comment]
Sure @DarthSim! I guess we should also add Accept-Encoding when GZipCompression is enabled?

**Comment by DarthSim** [comment]
Yeah, looks like we should, thanks

**Comment by leopangan** [comment]
@DarthSim done

**Comment by DarthSim** [comment]
Looks great, thanks!

**Pull request merged**
